services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./infrastructure/pg_auth:/var/lib/postgresql/data
  redis:
    image: redislabs/redis
    cap_add:
      - SYS_RESOURCE
    ports:
      - "8443:8443"
      - "9443:9443"
      - "12000:12000"
    volumes:
      - ./infrastructure/redis/persist:/var/opt/redislabs/persist
      - ./infrastructure/redis/tmp:/var/opt/redislabs/tmp
